
server:
  port: 9010
spring:
  application:
    name: zhi-blog-article
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: b7409ce8-7652-4054-8380-0747c68ff670
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:share-nacos-discovery.yml
      - nacos:zhi-blog-article.yml
      - nacos:share-datasource.yml
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        #未确认消息数量超过prefetch 不再向消费者推送消息
        prefetch: 100
    #发送到broker或exchange失败手动处理
    publisher-confirm-type: correlated
    #找不到queue时消息退回
    publisher-returns: true
    template:
      mandatory: true
