server:
  port: 9014
spring:
  application:
    name: zhi-blog-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: b7409ce8-7652-4054-8380-0747c68ff670
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:share-nacos-discovery.yml
      - nacos:zhi-blog-gateway.yml
oauth:
  key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl1+Edt/CU+M5vTYUZPQ6dP463x6jSGbuL/RMDf1wEkSKbxtL1jgyS6g9D4T85CujtJm5XgPrrSklY2aT7teaRMfb7U+YZMjJ8Yup6OBiou52CAfgqG4vNg2pi8CQGDJWRSDmnzSW9XxjRuhJMTilALUgRxvCsEAGhNJ0OumZwpIpQ3LrAq3bQ/TT3TjRWVRiazGhe9U0bU+vpzWztpyW/BfjoSipPfvUemzKOzCEZzerxzvJqHgwgO3o7LF5ETnuZPj8RdgXAjfOQgKCgODcNtvEg2I/+CcsrksqxaNrcI5cKFewYaZq6r/jeWwQETVwcoUbhXSArhaDuYZlDaWT0wIDAQAB
  white-urls: /*/druid/**,/oauth2/**,/favicon.ico,/webjars/**,/*/*/api-docs/**,/v3/api-docs/**,/swagger-ui.html
  block-urls: /*/druid/js/common.js