server:
  port: 9014
spring:
  application:
    name: zhi-blog-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: b7409ce8-7652-4054-8380-0747c68ff670
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:share-nacos-discovery.yml
      - nacos:zhi-blog-gateway.yml