server:
  port: 9016
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: zhi-blog-auth-server
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: b7409ce8-7652-4054-8380-0747c68ff670
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:share-nacos-discovery.yml
      - nacos:share-datasource.yml
      - nacos:zhi-blog-auth-server.yml
logging:
  level:
    root: info
    org.springframework.security: debug