server:
  port: 9011
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: zhi-blog-comment
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: b7409ce8-7652-4054-8380-0747c68ff670
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:share-nacos-discovery.yml
      - nacos:share-feign.yml
  swagger:
    title: ${spring.application.name}
    description: "评论模块"
    version: "v1.0.0"
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true